trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
- job: DeployLambda
  steps:

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/backend/post.py'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.SourcesDirectory)/backend/post.zip'
      replaceExistingArchive: true

    
  - task: LambdaDeployFunction@1
    inputs:
      awsCredentials: 'awsConnection'
      regionName: 'us-east-1'
      deploymentMode: 'codeonly'
      functionName: 'CDK-PostFuntionE67F3642-2IHt6C6QwWsA'
      codeLocation: 'localfile'
      localZipFile: '$(Build.SourcesDirectory)/backend/post.zip'
