trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: DeployLambda
  steps:

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'backend/post.py'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: 'backend/post.zip'
      replaceExistingArchive: true

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'backend/create.py'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: 'backend/create.zip'
      replaceExistingArchive: true


  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'backend/delete.py'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: 'backend/delete.zip'
      replaceExistingArchive: true

  

    
  - task: LambdaDeployFunction@1
    inputs:
      awsCredentials: 'awsConnection'
      regionName: 'us-east-1'
      deploymentMode: 'codeonly'
      functionName: 'CDK-PostFuntionE67F3642-2IHt6C6QwWsA'
      codeLocation: 'localfile'
      localZipFile: 'backend/post.zip'


  - task: LambdaDeployFunction@1
    inputs:
      awsCredentials: 'awsConnection'
      regionName: 'us-east-1'
      deploymentMode: 'codeonly'
      functionName: 'CDK-CreateFunction1693F3C7-HlhgOviHtLqT'
      codeLocation: 'localfile'
      localZipFile: 'backend/create.zip'


  - task: LambdaDeployFunction@1
    inputs:
      awsCredentials: 'awsConnection'
      regionName: 'us-east-1'
      deploymentMode: 'codeonly'
      functionName: 'CDK-DeleteFunction9052F8B5-KBdOxTsZup0t'
      codeLocation: 'localfile'
      localZipFile: 'backend/delete.zip'
